name: test on push

on:
  push:

jobs:
  test-on-push:
    runs-on: ubuntu-latest
    steps:

      - name: run-test
        uses: MikeSchulze/gdunit4-action@v1
        with:
          godot-version: '4.5'
          godot-net: true
          paths: 'res://tests' 
          
      - name: Check out code
        uses: actions/checkout@v2
        

